src/Oko.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using Oko.IsOAuthProvider;

namespace Oko.Web.Controllers
{
    public class AccountController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> OAuth()
        {
            await HttpContext.Authentication.ChallengeAsync(IsAuthenticationDefaults.AuthenticationScheme, new AuthenticationProperties()
            {
                RedirectUri = "/"
            });

            // TODO opravit
            return Content("Unauthorized");
        }
        
        [HttpGet]
        public IActionResult Logout()
        {
            throw new NotImplementedException();
        }

        [Authorize]
        [HttpGet]
        public IActionResult UserInfo()
        {
            return View();
        }
    }
}

src/Oko.Web/Controllers/AclController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Oko.Web.Authorization;

namespace Oko.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class AclController : Controller
    {
        private readonly AclRepository acl;

        public AclController(AclRepository acl)
        {
            this.acl = acl;
        }
        
        public IActionResult Index()
        {
            return View(acl.GetAllUsers());
        }
    }
}

src/Oko.Web/Controllers/CameraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Oko.Logic.Contract;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Oko.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class CameraController : Controller
    {
        private readonly ICameraRepository cameraRepository;

        public CameraController(ICameraRepository cameraRepository)
        {
            this.cameraRepository = cameraRepository;
        }

        public IActionResult List()
        {
            var cameras = cameraRepository.GetCameras();

            return View(cameras);
        }
    }
}

src/Oko.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Oko.Logic.Contract;
using Oko.Logic.Contract.Dto;
using Oko.Web.Authorization;

namespace Oko.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ICameraRepository cameraRepository;

        private readonly IImageRepository imageRepository;

        public HomeController(ICameraRepository cameraRepository, IImageRepository imageRepository)
        {
            this.cameraRepository = cameraRepository;
            this.imageRepository = imageRepository;
        }

        public IActionResult Index()
        {
            var zones = User.GetZones().ToArray();
            var cameras = cameraRepository.GetCamerasByZone(zones);

            return View(cameras);
        }

        [HttpGet]
        public IActionResult Images(string cameraName, DateTime day)
        {
            if(cameraName == null || day == null)
            {
                return BadRequest();
            }

            return Json(imageRepository.GetImages(cameraName, day));
        }

        [HttpGet]
        public IActionResult Image(string cameraName, DateTime day, string imageName)
        {
            if (cameraName == null || day == null || imageName == null)
            {
                return BadRequest();
            }

            Stream stream = imageRepository.GetImageStream(cameraName, day, imageName);

            if (stream == null)
            {
                return NotFound();
            }
            
            return File(stream, "application/jpeg");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Oko.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oko.Logic.Contract;

namespace Oko.Web.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageRepository imageRepository;

        public ImageController(IImageRepository imageRepository)
        {
            this.imageRepository = imageRepository;
        }
        
        public IActionResult GetImages(string cam, DateTime day)
        {
            var images = imageRepository.GetImages(cam, day);

            return new ObjectResult(images);
        }

        public IActionResult GetMultipleImages(string[] cams)
        {

            return null;
        }
    }
}

src/Oko.Web/Views/Acl/Index.cshtml
@model System.Collections.Generic.IEnumerable<Oko.Web.Authorization.AclItem>

<h2>ACL</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Uživatel</th>
            <th>Role</th>
            <th>Zóny</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@string.Join(", ", user.Roles)</td>
                <td>
                    @foreach (var z in user.Zones)
                    {
                        <code>@z</code>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

src/Oko.Web/Views/Camera/List.cshtml
@model IEnumerable<Oko.Logic.Contract.Dto.CameraDefinition>

<h2>Kamery</h2>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Název</th>
        <th>Místnost</th>
        <th>Zóna</th>
        <th>Popis</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var cam in Model)
        {
            <tr>
                <td>@cam.Name</td>
                <td>@cam.Room</td>
                <td><code>@cam.Zone</code></td>
                <td>@cam.Description</td>
            </tr>
        }
    </tbody>
</table>


src/Oko.Web/Views/Home/Index.cshtml
@using System.Globalization
@model IEnumerable<Oko.Logic.Contract.Dto.CameraDefinition>

@{
    ViewData["Title"] = "Archiv";
}
<div ng-controller="archive" ng-init="init()" ng-class="{debug: debug != false}">
    <div class="row" style="margin-top: 12px;">
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form class="form-inline">
                <div class="form-group form-group-sm">

                    <input type='text'
                           class="form-control day-input"
                           moment-picker="cursorTimeFormatted"
                           format="YYYY-MM-DD"
                           start-view="month"
                           max-view="month"
                           ng-model="cursorTime"
                           change="load()" />

                    <button class="btn btn-sm btn-default" ng-click="appendDays(-1)"><span class="glyphicon glyphicon-chevron-left"></span></button>
                    <button class="btn btn-sm btn-default" ng-click="appendDays(1)"><span class="glyphicon glyphicon-chevron-right"></span></button>
                </div>
            </form>
        </div>
        <div class="col-md-2 text-right zoom-btn-group">
            <button class="btn btn-sm btn-default" ng-click="timelineZoom('out')"><span class="glyphicon glyphicon-zoom-out"></span></button>
            <button class="btn btn-sm btn-default" ng-click="timelineZoom('in')"><span class="glyphicon glyphicon-zoom-in"></span></button>
            <button class="btn btn-sm btn-default" ng-click="timelineZoom('restore')"><span class="glyphicon glyphicon-fullscreen"></span></button>
        </div>
    </div>
    <span class="debug-info ng-hide" ng-cloak ng-show="debug != false">
        TIMELINE_SIZE={{timelineSize}}<br />
        TIMELINE_SCROLL={{timelineScroll}}<br />
        PINCH={{tlPinch}}<br />
        PAN={{tlPan}}
    </span>
    <div class="row">
        <div class="timeline-box" ng-class="{scroll: timelineSize > 100}">
            <div class="timeline-box-scroll" style="width: {{timelineSize}}%" hm-pinch="timelinePinch($event)" hm-pan="timelinePan($event)" own-scroll-x="timelineScroll">
                <div class="timeline-cams">
                    <div class="timeline-header">
                        <b style="left: {{calcPosition(cursorTime)}}%" id="pointer"><span>&#9660;</span></b>
                    </div>

                    @foreach (var c in Model)
                    {
                        <div class="cam" ng-init="initCamera('@c.Name')">
                            <span>@c.Name</span>
                            <div class="pickers">
                                <i ng-repeat="i in cameras['@c.Name'].timeline" ng-cloak style="left: {{calcPosition(i.time)}}%" ng-click="showImage(i.time)"></i>
                            </div>
                        </div>
                    }

                </div>

                <div class="timeline-footer">
                    @for (int i = 0; i <= 24; i++)
                    {
                        <i style="left: @((i*100/24d).ToString("f", CultureInfo.InvariantCulture))%;"></i>
                        <b style="left: @((i*100/24d).ToString("f", CultureInfo.InvariantCulture))%;"><span>@i</span></b>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="row nav-btn">
        <div class="col-md-4 col-xs-4 col-sm-4">
            <button class="btn btn-xs btn-default" ng-click="appendMinutes(-1)"><span class="glyphicon glyphicon-step-backward"></span> Minuta</button>
            <button class="btn btn-xs btn-default" ng-click="navigateOverImage(-1)"><span class="glyphicon glyphicon-backward"></span> Snímek</button>
            <button class="btn btn-xs btn-default ng-hide disabled"><span class="glyphicon glyphicon-backward"></span> Událost</button>
        </div>
        <div class="col-md-4 col-xs-4 col-sm-4 text-center">
            <span class="ng-hide" ng-cloak ng-show="cursorTime != false" ng-click="openDebug()">{{cursorTime| amDateFormat:'HH:mm:ss'}}</span>
        </div>
        <div class="col-md-4 col-xs-4 col-sm-4 text-right">
            <button class="btn btn-xs btn-default  ng-hide disabled">Událost <span class="glyphicon glyphicon-forward"></span></button>
            <button class="btn btn-xs btn-default" ng-click="navigateOverImage(1)">Snímek <span class="glyphicon glyphicon-forward"></span></button>
            <button class="btn btn-xs btn-default" ng-click="appendMinutes(1)">Minuta <span class="glyphicon glyphicon-step-forward"></span></button>
        </div>
    </div>

    <span class="debug-info ng-hide" ng-cloak ng-show="debug != false">
        BOX_CLASS={{cameraBoxClass}}<br />
        DATE={{cursorTime| amDateFormat:'YYYY-MM-DD HH:mm:ss'}}
    </span>
    <div class="row" id="image-box">
        <div class="camera-image-box {{cam.style}}" ng-repeat="cam in cameras" ng-class="cameraBoxClass">
            <img ng-src="{{imagePath(cam)}}" ng-class="cam.style" ng-click="openDetil(cam)" />
            <span class="name" ng-cloak>{{cam.name}}</span>
            <span class="debug-info" ng-cloak ng-show="debug != false">
                IMG={{cam.image}}<br />
                PATH={{imagePath(cam)}}<br />
                AGE={{calcAge(cam.image.time)}}<br />
                STYLE={{cam.style}}
            </span>
            <span class="image-navigation minute left" ng-click="appendMinutes(-1)"></span>
            <span class="image-navigation frame left" ng-click="navigateOverImage(-1)"></span>
            <span class="image-navigation minute right" ng-click="appendMinutes(1)"></span>
            <span class="image-navigation frame right" ng-click="navigateOverImage(1)"></span>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="modal image-detail" ng-class="{show: detail != false}" ng-click="closeDetail()" >
        
        <img ng-src="{{imagePath(detail)}}" 
             ng-class="detail.style" />

        <span class="debug-info" ng-cloak ng-show="debug != false">
            STYLE={{detail.style}}<br />
            IMAGE={{detail.image}}<br />
            PITCH={{imPinch}}<br />
            PAN={{imPan}}<br />
        </span>
    </div>
</div>

src/Oko.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    Layout = "_RootLayout";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><span class="glyphicon glyphicon-camera"></span> OKO</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Archiv</a></li>
                @if (User.IsInRole("admin"))
                {
                    <li><a asp-area="" asp-controller="Camera" asp-action="List">Kamery</a></li>
                    <li><a asp-area="" asp-controller="Acl" asp-action="Index">ACL</a></li>
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-controller="Account" asp-action="UserInfo">@User.FindFirst(ClaimTypes.GivenName).Value</a></li>
                <li><a asp-area="" asp-controller="Account" asp-action="Logout">Odhlásit</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; 2017 - Oko</p>
    </footer>
</div>

src/Oko.Web/Views/Shared/_RootLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OKO</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/timeline.css" />
        <link rel="stylesheet" href="~/lib/angular-moment-picker/dist/angular-moment-picker.css" />
        
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/timeline.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/angular-moment-picker/dist/angular-moment-picker.min.css" />
    </environment>
</head>
<body ng-app="okoApp">
    
    @RenderBody()
    
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/angular/angular.min.js"></script>
        <script src="~/lib/moment/moment.js"></script>
        <script src="~/lib/angular-moment/angular-moment.js"></script>
        <script src="~/lib/angular-moment-picker/dist/angular-moment-picker.js"></script>
        <script src="~/lib/hammerjs/hammer.js"></script>
        <script src="~/lib/angular-gestures/gestures.js"></script>

        <script src="~/js/site.js"></script>
        <script src="~/js/archive-ng.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/lib/angular/angular.js" asp-append-version="true"></script>
        <script src="~/lib/moment/min/moment.min.js" asp-append-version="true"></script>
        <script src="~/lib/angular-moment/angular-moment.min.js" asp-append-version="true"></script>
        <script src="~/lib/angular-moment-picker/dist/angular-moment-picker.min.js" asp-append-version="true"></script>
        <script src="~/lib/hammerjs/hammer.min.js" asp-append-version="true"></script>
        <script src="~/lib/angular-gestures/gestures.min.js" asp-append-version="true"></script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/archive-ng.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>